#!/bin/sh

# Generated by convert.go. DO NOT EDIT.

DIR=$(dirname $BASH_SOURCE)

mongoimport --uri=mongodb://localhost/world --collection=city --drop --maintainInsertionOrder $DIR/city.json
mongoimport --uri=mongodb://localhost/world --collection=country --drop --maintainInsertionOrder $DIR/country.json
