// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package sakila

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type actorTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *actorTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("actor").
func (v *actorTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *actorTableType) Columns() []string {
	return []string{
		"actor_id",
		"first_name",
		"last_name",
		"last_update",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *actorTableType) NewStruct() reform.Struct {
	return new(Actor)
}

// NewRecord makes a new record for that table.
func (v *actorTableType) NewRecord() reform.Record {
	return new(Actor)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *actorTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ActorTable represents actor view or table in SQL database.
var ActorTable = &actorTableType{
	s: parse.StructInfo{
		Type:    "Actor",
		SQLName: "actor",
		Fields: []parse.FieldInfo{
			{Name: "ActorID", Type: "int16", Column: "actor_id"},
			{Name: "FirstName", Type: "string", Column: "first_name"},
			{Name: "LastName", Type: "string", Column: "last_name"},
			{Name: "LastUpdate", Type: "time.Time", Column: "last_update"},
		},
		PKFieldIndex: 0,
	},
	z: new(Actor).Values(),
}

// String returns a string representation of this struct or record.
func (s Actor) String() string {
	res := make([]string, 4)
	res[0] = "ActorID: " + reform.Inspect(s.ActorID, true)
	res[1] = "FirstName: " + reform.Inspect(s.FirstName, true)
	res[2] = "LastName: " + reform.Inspect(s.LastName, true)
	res[3] = "LastUpdate: " + reform.Inspect(s.LastUpdate, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Actor) Values() []interface{} {
	return []interface{}{
		s.ActorID,
		s.FirstName,
		s.LastName,
		s.LastUpdate,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Actor) Pointers() []interface{} {
	return []interface{}{
		&s.ActorID,
		&s.FirstName,
		&s.LastName,
		&s.LastUpdate,
	}
}

// View returns View object for that struct.
func (s *Actor) View() reform.View {
	return ActorTable
}

// Table returns Table object for that record.
func (s *Actor) Table() reform.Table {
	return ActorTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Actor) PKValue() interface{} {
	return s.ActorID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Actor) PKPointer() interface{} {
	return &s.ActorID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Actor) HasPK() bool {
	return s.ActorID != ActorTable.z[ActorTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.ActorID = pk.
func (s *Actor) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = ActorTable
	_ reform.Struct = (*Actor)(nil)
	_ reform.Table  = ActorTable
	_ reform.Record = (*Actor)(nil)
	_ fmt.Stringer  = (*Actor)(nil)
)

func init() {
	parse.AssertUpToDate(&ActorTable.s, new(Actor))
}
