// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package pagila

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type paymentViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *paymentViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("payment").
func (v *paymentViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *paymentViewType) Columns() []string {
	return []string{
		"payment_id",
		"customer_id",
		"staff_id",
		"rental_id",
		"amount",
		"payment_date",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *paymentViewType) NewStruct() reform.Struct {
	return new(Payment)
}

// PaymentView represents payment view or table in SQL database.
var PaymentView = &paymentViewType{
	s: parse.StructInfo{
		Type:    "Payment",
		SQLName: "payment",
		Fields: []parse.FieldInfo{
			{Name: "PaymentID", Type: "int32", Column: "payment_id"},
			{Name: "CustomerID", Type: "int32", Column: "customer_id"},
			{Name: "StaffID", Type: "int32", Column: "staff_id"},
			{Name: "RentalID", Type: "int32", Column: "rental_id"},
			{Name: "Amount", Type: "string", Column: "amount"},
			{Name: "PaymentDate", Type: "time.Time", Column: "payment_date"},
		},
		PKFieldIndex: -1,
	},
	z: new(Payment).Values(),
}

// String returns a string representation of this struct or record.
func (s Payment) String() string {
	res := make([]string, 6)
	res[0] = "PaymentID: " + reform.Inspect(s.PaymentID, true)
	res[1] = "CustomerID: " + reform.Inspect(s.CustomerID, true)
	res[2] = "StaffID: " + reform.Inspect(s.StaffID, true)
	res[3] = "RentalID: " + reform.Inspect(s.RentalID, true)
	res[4] = "Amount: " + reform.Inspect(s.Amount, true)
	res[5] = "PaymentDate: " + reform.Inspect(s.PaymentDate, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Payment) Values() []interface{} {
	return []interface{}{
		s.PaymentID,
		s.CustomerID,
		s.StaffID,
		s.RentalID,
		s.Amount,
		s.PaymentDate,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Payment) Pointers() []interface{} {
	return []interface{}{
		&s.PaymentID,
		&s.CustomerID,
		&s.StaffID,
		&s.RentalID,
		&s.Amount,
		&s.PaymentDate,
	}
}

// View returns View object for that struct.
func (s *Payment) View() reform.View {
	return PaymentView
}

// check interfaces
var (
	_ reform.View   = PaymentView
	_ reform.Struct = (*Payment)(nil)
	_ fmt.Stringer  = (*Payment)(nil)
)

func init() {
	parse.AssertUpToDate(&PaymentView.s, new(Payment))
}
