// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package pagila

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type storeTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *storeTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("store").
func (v *storeTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *storeTableType) Columns() []string {
	return []string{
		"store_id",
		"manager_staff_id",
		"address_id",
		"last_update",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *storeTableType) NewStruct() reform.Struct {
	return new(Store)
}

// NewRecord makes a new record for that table.
func (v *storeTableType) NewRecord() reform.Record {
	return new(Store)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *storeTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// StoreTable represents store view or table in SQL database.
var StoreTable = &storeTableType{
	s: parse.StructInfo{
		Type:    "Store",
		SQLName: "store",
		Fields: []parse.FieldInfo{
			{Name: "StoreID", Type: "int32", Column: "store_id"},
			{Name: "ManagerStaffID", Type: "int32", Column: "manager_staff_id"},
			{Name: "AddressID", Type: "int32", Column: "address_id"},
			{Name: "LastUpdate", Type: "time.Time", Column: "last_update"},
		},
		PKFieldIndex: 0,
	},
	z: new(Store).Values(),
}

// String returns a string representation of this struct or record.
func (s Store) String() string {
	res := make([]string, 4)
	res[0] = "StoreID: " + reform.Inspect(s.StoreID, true)
	res[1] = "ManagerStaffID: " + reform.Inspect(s.ManagerStaffID, true)
	res[2] = "AddressID: " + reform.Inspect(s.AddressID, true)
	res[3] = "LastUpdate: " + reform.Inspect(s.LastUpdate, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Store) Values() []interface{} {
	return []interface{}{
		s.StoreID,
		s.ManagerStaffID,
		s.AddressID,
		s.LastUpdate,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Store) Pointers() []interface{} {
	return []interface{}{
		&s.StoreID,
		&s.ManagerStaffID,
		&s.AddressID,
		&s.LastUpdate,
	}
}

// View returns View object for that struct.
func (s *Store) View() reform.View {
	return StoreTable
}

// Table returns Table object for that record.
func (s *Store) Table() reform.Table {
	return StoreTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Store) PKValue() interface{} {
	return s.StoreID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Store) PKPointer() interface{} {
	return &s.StoreID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Store) HasPK() bool {
	return s.StoreID != StoreTable.z[StoreTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.StoreID = pk.
func (s *Store) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = StoreTable
	_ reform.Struct = (*Store)(nil)
	_ reform.Table  = StoreTable
	_ reform.Record = (*Store)(nil)
	_ fmt.Stringer  = (*Store)(nil)
)

func init() {
	parse.AssertUpToDate(&StoreTable.s, new(Store))
}
