// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package sakila

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type paymentTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *paymentTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("payment").
func (v *paymentTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *paymentTableType) Columns() []string {
	return []string{
		"payment_id",
		"customer_id",
		"staff_id",
		"rental_id",
		"amount",
		"payment_date",
		"last_update",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *paymentTableType) NewStruct() reform.Struct {
	return new(Payment)
}

// NewRecord makes a new record for that table.
func (v *paymentTableType) NewRecord() reform.Record {
	return new(Payment)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *paymentTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// PaymentTable represents payment view or table in SQL database.
var PaymentTable = &paymentTableType{
	s: parse.StructInfo{
		Type:    "Payment",
		SQLName: "payment",
		Fields: []parse.FieldInfo{
			{Name: "PaymentID", Type: "int16", Column: "payment_id"},
			{Name: "CustomerID", Type: "int16", Column: "customer_id"},
			{Name: "StaffID", Type: "int8", Column: "staff_id"},
			{Name: "RentalID", Type: "*int32", Column: "rental_id"},
			{Name: "Amount", Type: "string", Column: "amount"},
			{Name: "PaymentDate", Type: "time.Time", Column: "payment_date"},
			{Name: "LastUpdate", Type: "*time.Time", Column: "last_update"},
		},
		PKFieldIndex: 0,
	},
	z: new(Payment).Values(),
}

// String returns a string representation of this struct or record.
func (s Payment) String() string {
	res := make([]string, 7)
	res[0] = "PaymentID: " + reform.Inspect(s.PaymentID, true)
	res[1] = "CustomerID: " + reform.Inspect(s.CustomerID, true)
	res[2] = "StaffID: " + reform.Inspect(s.StaffID, true)
	res[3] = "RentalID: " + reform.Inspect(s.RentalID, true)
	res[4] = "Amount: " + reform.Inspect(s.Amount, true)
	res[5] = "PaymentDate: " + reform.Inspect(s.PaymentDate, true)
	res[6] = "LastUpdate: " + reform.Inspect(s.LastUpdate, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Payment) Values() []interface{} {
	return []interface{}{
		s.PaymentID,
		s.CustomerID,
		s.StaffID,
		s.RentalID,
		s.Amount,
		s.PaymentDate,
		s.LastUpdate,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Payment) Pointers() []interface{} {
	return []interface{}{
		&s.PaymentID,
		&s.CustomerID,
		&s.StaffID,
		&s.RentalID,
		&s.Amount,
		&s.PaymentDate,
		&s.LastUpdate,
	}
}

// View returns View object for that struct.
func (s *Payment) View() reform.View {
	return PaymentTable
}

// Table returns Table object for that record.
func (s *Payment) Table() reform.Table {
	return PaymentTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Payment) PKValue() interface{} {
	return s.PaymentID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Payment) PKPointer() interface{} {
	return &s.PaymentID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Payment) HasPK() bool {
	return s.PaymentID != PaymentTable.z[PaymentTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.PaymentID = pk.
func (s *Payment) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = PaymentTable
	_ reform.Struct = (*Payment)(nil)
	_ reform.Table  = PaymentTable
	_ reform.Record = (*Payment)(nil)
	_ fmt.Stringer  = (*Payment)(nil)
)

func init() {
	parse.AssertUpToDate(&PaymentTable.s, new(Payment))
}
