// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package sakila

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type staffListViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *staffListViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("staff_list").
func (v *staffListViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *staffListViewType) Columns() []string {
	return []string{
		"ID",
		"name",
		"address",
		"zip code",
		"phone",
		"city",
		"country",
		"SID",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *staffListViewType) NewStruct() reform.Struct {
	return new(StaffList)
}

// StaffListView represents staff_list view or table in SQL database.
var StaffListView = &staffListViewType{
	s: parse.StructInfo{
		Type:    "StaffList",
		SQLName: "staff_list",
		Fields: []parse.FieldInfo{
			{Name: "ID", Type: "int8", Column: "ID"},
			{Name: "Name", Type: "*string", Column: "name"},
			{Name: "Address", Type: "string", Column: "address"},
			{Name: "ZipCode", Type: "*string", Column: "zip code"},
			{Name: "Phone", Type: "string", Column: "phone"},
			{Name: "City", Type: "string", Column: "city"},
			{Name: "Country", Type: "string", Column: "country"},
			{Name: "SID", Type: "int8", Column: "SID"},
		},
		PKFieldIndex: -1,
	},
	z: new(StaffList).Values(),
}

// String returns a string representation of this struct or record.
func (s StaffList) String() string {
	res := make([]string, 8)
	res[0] = "ID: " + reform.Inspect(s.ID, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "Address: " + reform.Inspect(s.Address, true)
	res[3] = "ZipCode: " + reform.Inspect(s.ZipCode, true)
	res[4] = "Phone: " + reform.Inspect(s.Phone, true)
	res[5] = "City: " + reform.Inspect(s.City, true)
	res[6] = "Country: " + reform.Inspect(s.Country, true)
	res[7] = "SID: " + reform.Inspect(s.SID, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *StaffList) Values() []interface{} {
	return []interface{}{
		s.ID,
		s.Name,
		s.Address,
		s.ZipCode,
		s.Phone,
		s.City,
		s.Country,
		s.SID,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *StaffList) Pointers() []interface{} {
	return []interface{}{
		&s.ID,
		&s.Name,
		&s.Address,
		&s.ZipCode,
		&s.Phone,
		&s.City,
		&s.Country,
		&s.SID,
	}
}

// View returns View object for that struct.
func (s *StaffList) View() reform.View {
	return StaffListView
}

// check interfaces
var (
	_ reform.View   = StaffListView
	_ reform.Struct = (*StaffList)(nil)
	_ fmt.Stringer  = (*StaffList)(nil)
)

func init() {
	parse.AssertUpToDate(&StaffListView.s, new(StaffList))
}
