// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package pagila

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type filmActorViewType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *filmActorViewType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("film_actor").
func (v *filmActorViewType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *filmActorViewType) Columns() []string {
	return []string{
		"actor_id",
		"film_id",
		"last_update",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *filmActorViewType) NewStruct() reform.Struct {
	return new(FilmActor)
}

// FilmActorView represents film_actor view or table in SQL database.
var FilmActorView = &filmActorViewType{
	s: parse.StructInfo{
		Type:    "FilmActor",
		SQLName: "film_actor",
		Fields: []parse.FieldInfo{
			{Name: "ActorID", Type: "int32", Column: "actor_id"},
			{Name: "FilmID", Type: "int32", Column: "film_id"},
			{Name: "LastUpdate", Type: "time.Time", Column: "last_update"},
		},
		PKFieldIndex: -1,
	},
	z: new(FilmActor).Values(),
}

// String returns a string representation of this struct or record.
func (s FilmActor) String() string {
	res := make([]string, 3)
	res[0] = "ActorID: " + reform.Inspect(s.ActorID, true)
	res[1] = "FilmID: " + reform.Inspect(s.FilmID, true)
	res[2] = "LastUpdate: " + reform.Inspect(s.LastUpdate, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *FilmActor) Values() []interface{} {
	return []interface{}{
		s.ActorID,
		s.FilmID,
		s.LastUpdate,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *FilmActor) Pointers() []interface{} {
	return []interface{}{
		&s.ActorID,
		&s.FilmID,
		&s.LastUpdate,
	}
}

// View returns View object for that struct.
func (s *FilmActor) View() reform.View {
	return FilmActorView
}

// check interfaces
var (
	_ reform.View   = FilmActorView
	_ reform.Struct = (*FilmActor)(nil)
	_ fmt.Stringer  = (*FilmActor)(nil)
)

func init() {
	parse.AssertUpToDate(&FilmActorView.s, new(FilmActor))
}
