// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package sakila

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type filmTextTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *filmTextTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("film_text").
func (v *filmTextTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *filmTextTableType) Columns() []string {
	return []string{
		"film_id",
		"title",
		"description",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *filmTextTableType) NewStruct() reform.Struct {
	return new(FilmText)
}

// NewRecord makes a new record for that table.
func (v *filmTextTableType) NewRecord() reform.Record {
	return new(FilmText)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *filmTextTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// FilmTextTable represents film_text view or table in SQL database.
var FilmTextTable = &filmTextTableType{
	s: parse.StructInfo{
		Type:    "FilmText",
		SQLName: "film_text",
		Fields: []parse.FieldInfo{
			{Name: "FilmID", Type: "int16", Column: "film_id"},
			{Name: "Title", Type: "string", Column: "title"},
			{Name: "Description", Type: "*string", Column: "description"},
		},
		PKFieldIndex: 0,
	},
	z: new(FilmText).Values(),
}

// String returns a string representation of this struct or record.
func (s FilmText) String() string {
	res := make([]string, 3)
	res[0] = "FilmID: " + reform.Inspect(s.FilmID, true)
	res[1] = "Title: " + reform.Inspect(s.Title, true)
	res[2] = "Description: " + reform.Inspect(s.Description, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *FilmText) Values() []interface{} {
	return []interface{}{
		s.FilmID,
		s.Title,
		s.Description,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *FilmText) Pointers() []interface{} {
	return []interface{}{
		&s.FilmID,
		&s.Title,
		&s.Description,
	}
}

// View returns View object for that struct.
func (s *FilmText) View() reform.View {
	return FilmTextTable
}

// Table returns Table object for that record.
func (s *FilmText) Table() reform.Table {
	return FilmTextTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *FilmText) PKValue() interface{} {
	return s.FilmID
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *FilmText) PKPointer() interface{} {
	return &s.FilmID
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *FilmText) HasPK() bool {
	return s.FilmID != FilmTextTable.z[FilmTextTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.FilmID = pk.
func (s *FilmText) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = FilmTextTable
	_ reform.Struct = (*FilmText)(nil)
	_ reform.Table  = FilmTextTable
	_ reform.Record = (*FilmText)(nil)
	_ fmt.Stringer  = (*FilmText)(nil)
)

func init() {
	parse.AssertUpToDate(&FilmTextTable.s, new(FilmText))
}
